apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-qr-workflow
  labels:
    app: new-qr-workflow
  namespace: qr-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-qr-workflow
  template:
    metadata:
      labels:
        app: new-qr-workflow
    spec:
      containers:
        - name: new-qr-workflow
          image: badgesacr1.azurecr.io/image-workflow-1713941648098:latest
          ports:
            - containerPort: 8000