apiVersion: v1
kind: Service
metadata:
  name: new-qr-workflow
  namespace: qr-gen
spec:
  type: LoadBalancer
  selector:
    app: new-qr-workflow
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000