apiVersion: v1
kind: Service
metadata:
  name: badges-qrcode-generator
  namespace: qr-gen
spec:
  type: LoadBalancer
  selector:
    app: badges-qrcode-generator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000